### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by Boomatisch** [Walsheyy/WMServerSirens#1]
Hello!,
nice Release!. I use it on my Server. I want to ask if it is possible to "stream" a custom Police Horn? So if anybody press E we hear a other Police Horn ... is that possible? And can we add Custom Siren's for Police and for Fire? 

I use LuxVehiclecontrol :) 
I hope you can help me
Friendly Regards
Boomatisch

**Comment by arthur-rl** [comment]
It explains it in the [readme](https://github.com/Walsheyy/WMServerSirens/blob/master/README.md)
