### ISSUE TITLE
doenst work with els

### ISSUE THREAD

**Issue by Aspect1312** [Walsheyy/WMServerSirens#2]
i have elsplus because my vehicles need that but it doenst work with this script how do i fix this or what do i need to change in the els file for the vehicle?

**Comment by Jaccosf** [comment]
It does work if you download the latest elsplus version out of their discord (0.2.3.203).

**Comment by Aspect1312** [comment]
> It does work if you download the latest elsplus version out of their discord (0.2.3.203).

Whats their discord i cant find it

**Comment by NielsNotsmurf** [comment]
friendsincode discord
