### ISSUE TITLE
doenst work with MrDaGree/ELS-FiveM

### ISSUE THREAD

**Issue by Baduzinh** [Walsheyy/WMServerSirens#3]
I have MrDaGree/ELS-FiveM my vehicles need it to work the leds, I followed the installation video I configured lux_vehcontrol as necessary, but it doesn't work the sound of the sirens, how do I fix this or what do I need to do?

**Comment by Walsheyy** [comment]
Please ask for support in the discord channel as this question has already been resolved there.

**Comment by DevKilo1** [comment]
I got this to work on my own, I'm willing to share my code to anybody who requests.
