### ISSUE TITLE
Sirens still default

### ISSUE THREAD

**Issue by InfoBlock** [Walsheyy/WMServerSirens#5]
I've changed the Sirens to Custom Sirens, restarted the Server, Script started successfully but the Sirens are still the default GTA Sirens

**Comment by blk07shelbygt** [comment]
> I've changed the Sirens to Custom Sirens, restarted the Server, Script started successfully but the Sirens are still the default GTA Sirens

Did you configure the game name and set the siren in lux?

**Comment by InfoBlock** [comment]
i dont have lux as it doesnt work properly on my server

**Comment by blk07shelbygt** [comment]
Never heard anyone have an issue of it not working properly unless user error. What do you use so I can look it up and help you figure out the issue. I use the newest version of Lux and this resource works flawlessly.

**Comment by Walsheyy** [comment]
Upload your client.lua to pastebin and paste in the link so we can review the code.
