### ISSUE TITLE
Server crashes with the updates to lux_vehiclecontrol

### ISSUE THREAD

**Issue by Intelligentzombie29** [Walsheyy/WMServerSirens#6]
hey, i have been looking for a script like this for a while and tried to use it, followed your video on how to install them, but when i edit the lux_vehcontrol client.lua with what you have my server crashes players out
![error1](https://user-images.githubusercontent.com/63502847/140807480-d9f9efae-fd0c-466c-8f92-f81ccfd62f1d.jpg)
![error3](https://user-images.githubusercontent.com/63502847/140807485-fa01eb5f-b014-4f0d-9f34-14180e38549b.jpg)
![error 2](https://user-images.githubusercontent.com/63502847/140807488-7c360e82-0a71-4847-aca1-f4ec6e8f186e.jpg)
.

**Comment by Walsheyy** [comment]
Hello, this is unrelated to our resource. You would need to get in contact with the script owner.
