### ISSUE TITLE
Audio 'render distance'

### ISSUE THREAD

**Issue by matsn0w** [Walsheyy/WMServerSirens#7]
Hey there,

We noticed that when player A starts driving with the sirens on (custom sound) and drives to player B, player B hears the default GTA siren in stead of the custom sound. Player A hears the correct sound. This only happens if the siren was started quite far away from player A. When started within a certain range, this problem doesn't exist.

So is there some kind of 'rendering distance' but for audio going on?
Anyone else experiencing this issue?

**Comment by Walsheyy** [comment]
Have you tried using this native? https://docs.fivem.net/natives/?_0x552369F549563AD5
